apps/account/urls.py
from django.urls import path, include
from django.contrib.auth.views import LoginView
from django.views.generic.base import TemplateView
from apps.account import forms, views

app_name = 'account'
urlpatterns = [
    path('login/', views.Login.as_view(), name='login'),
    path('signup/', views.SignUp.as_view(), name='signup'),
    path('', include('django.contrib.auth.urls')),
    path('u/<int:pk>/edit/', views.UpdateProfile.as_view(), name='edit'),
    path('u/<int:pk>/', views.UserDetail.as_view(), name='user_detail'),
    path('u/<int:pk>/participations/', views.UserParticipations.as_view(), name='participations'),
]

apps/competition/urls.py
from django.urls import path
from apps.competition import views
from apps.competition.apps import CompetitionConfig

app_name = 'competition'
urlpatterns = [
    path('', views.ListCompetition.as_view(), name='list'),
    path('create/', views.CreateCompetitionView.as_view(), name='createcompetition'),
    path('id/<int:pk>/', views.CompetitionDetail.as_view(), name='detail'),
    path('id/<int:pk>/edit/', views.CompetitionUpdate.as_view(), name='edit'),
    path('id/<int:pk>/delete/', views.CompetitionDelete.as_view(), name='delete'),
    path('id/<int:pk>/finish/', views.CompetitionFinish.as_view(), name='finish'),
    path('id/<int:pk>/create-team/', views.CreateTeam.as_view(), name='create-team'),
    path('id/<int:pk>/submit-answer/', views.PublishAnswerCompetition.as_view(), name='submit-answer'),
    path('id/<int:pk>/valorate-submitions/', views.RateAnswerCompetition.as_view(), name='valorate-submitions'),

    path('search/', views.SearchCompetitions.as_view(), name="search"),
]

apps/league/urls.py
from django.urls import path
from apps.league import views

app_name='league'
urlpatterns = [
    path('', views.Home.as_view(), name='home'),
    path('info/', views.Info.as_view(), name='info'),
]

codeleague/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic.base import TemplateView

urlpatterns = [
                  path('', include('apps.league.urls')),
                  path('admin/', admin.site.urls),
                  path('accounts/', include('apps.account.urls')),
                  path('competition/', include('apps.competition.urls')),
                  path('category/', include('apps.category.urls')),
              ] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

apps/league/models.py
from django.core.exceptions import ValidationError
from django.db import models

# Create your models here.
from django.db.models.functions import datetime
from django.utils import timezone
from django.conf import settings
from django.utils.timezone import make_aware, get_current_timezone

from apps.account.models import LeagueUser


class Category(models.Model):
    name = models.CharField(max_length=25, unique=True)
    description = models.TextField()

    def __str__(self):
        return f'Category {self.name}'


class Files(models.Model):
    title = models.CharField(max_length=50)
    file_bucket = models.CharField(max_length=255, default=None)

    @classmethod
    def create(cls, title, file_bucket):
        file_upload = cls(title=title, file_bucket=file_bucket)
        return file_upload

    def __str__(self):
        return f'Title {self.title} file{self.file_bucket}'


class Competition(models.Model):
    title = models.CharField(max_length=50)
    description = models.TextField()
    owner = models.ForeignKey(LeagueUser, on_delete=models.CASCADE, null=True)
    data_start_inscription = models.DateTimeField(default=timezone.now)
    data_finish_inscription = models.DateTimeField()
    data_start_competition = models.DateTimeField()
    data_finish_competition = models.DateTimeField()
    categories = models.ManyToManyField(Category, blank=True)
    files = models.ManyToManyField(Files, blank=True)
    finalized = models.BooleanField(default=False)

    def __str__(self):
        return f'{self.title}'

    def save(self, **kwargs):
        if self.data_start_inscription < self.data_finish_inscription < self.data_finish_competition and \
                self.data_start_competition < self.data_finish_competition:
            super(Competition, self).save(**kwargs)
        else:
            raise ValidationError("Dates are not correct.")

    def is_inscription_opened(self):
        if self.data_start_inscription <= timezone.now() < self.data_finish_inscription:
            return True
        return False

    def is_competition_opened(self):
        if self.data_start_competition <= timezone.now() < self.data_finish_competition:
            return True
        return False

    def is_competition_ended(self):
        if timezone.now() > self.data_finish_inscription:
            return True
        return False


class Submit(models.Model):
    description = models.TextField()
    githuburl = models.URLField(blank=True, max_length=200)
    files = models.ManyToManyField(Files, blank=True)
    submit_date = models.DateField(auto_now=True)
    team_id = models.IntegerField(null=True)

    def __str__(self):
        return f'Submision at day ({self.submit_date})'


class Team(models.Model):
    name = models.CharField(max_length=25, unique=True)
    ranking = models.ForeignKey('Ranking', on_delete=models.CASCADE, null=True)
    members = models.ManyToManyField(LeagueUser, related_name='participants')
    competition = models.ForeignKey(Competition, on_delete=models.SET_NULL, null=True)
    submition = models.ForeignKey(Submit, on_delete=models.CASCADE, null=True, blank=True)

    def __str__(self):
        return f'Team {self.name} in {self.competition} : {self.members.all()}'


class Ranking(models.Model):
    score = models.PositiveIntegerField(null=False, default=0)

    def __str__(self):
        return f'Ranking: {self.score}'

    @classmethod
    def create(cls, score):
        ranking = cls(score=score)
        return ranking

apps/league/views.py
from apps.league.models import Competition

# Create your views here.
from django.views import generic


class Home(generic.ListView):
    model = Competition
    context_object_name = 'competitions'
    template_name = 'home.html'

    def get_queryset(self, *args, **kwargs):
        return filter(lambda x: x.is_inscription_opened(), self.model.objects.all().order_by('data_finish_competition'))


class Info(generic.TemplateView):
    template_name = 'info.html'

apps/league/templates/home/auth.html
{% load static %}
<div class="container-fluid text-center">
    <img class="center-fit" width="40%" src="{% static 'imgs/CodeleagueTransp.png' %}" alt="Architecture">
</div><br><br>
{% include "home/competlist.html" %}

apps/league/templates/home/competlist.html
{% load static %}
<div class="container" xmlns:competition="http://www.w3.org/1999/xhtml" >
    <div class="container-fluid text-center">
        <h1>COMPETITIONS</h1>
    </div>
    <br>
    <div class="row pb-3 ">
        {% for compet in competitions|slice:":6" %}
            <div class="col-6 pb-3 d-flex align-items-stretch">
                <div class="card h-200" style="width: 36rem;" name="card_{{ compet.title }}">
                    <div class="card-body">
                        {% if compet.owner == user %}
                            <a href="{% url 'competition:edit' compet.pk %}"
                               class="btn btn-outline-primary float-right">
                                <img width="20px"
                                     src="{% static 'imgs/icons/edit.png' %}">Edit
                            </a>
                        {% endif %}
                        <div class="row">
                            <div class="col-12">
                                <h4 class="card-title">{{ compet.title }}{% if compet.is_competition_opened %}
                                    <span class="badge badge-success"
                                          style="background-color: #74DA47; border-color: #74DA47; color: #000">In progress</span>
                                {% elif compet.is_inscription_opened %}
                                    <span class="badge badge-warning"
                                          style="background-color: #dacb47; border-color: #dacb47; color: #000">Inscriptions</span>
                                {% else %}
                                    <span class="badge badge-warning"
                                          style="background-color: #EF3B3B; border-color: #EF3B3B; color: #000">Closed</span>

                                {% endif %}</h4>
                            </div>

                        </div>
                        {% if compet.is_inscription_opened %}
                            <span class="badge badge-success"
                                  style="background-color: #74DA47; border-color: #74DA47; color: #000">Inscriptions opened</span>
                        {% else %}
                            <span class="badge badge-danger"
                                  style="background-color: #EF3B3B; border-color: #EF3B3B; color: #000">Inscriptions closed</span>
                        {% endif %}

                        <p class="card-text pt-3">
                            {{ compet.description|slice:"0:200" }}...


                        </p><br>
                        <div class="row">
                            <div class="col-9">
                                <div class="container row">
                                    <h6>Date: {{ compet.data_start_competition|date:"SHORT_DATE_FORMAT" }} -
                                        {{ compet.data_finish_competition|date:"SHORT_DATE_FORMAT" }}</h6>
                                </div>
                                <div class="container row">
                                    <h6>Time: {{ compet.data_start_competition|time }}
                                        - {{ compet.data_finish_competition|time }}</h6>
                                </div>
                            </div>

                            <div class="col-3">
                                <a href="#" class="btn badge-pill btn-primary float-right" data-toggle="modal"
                                   data-target="#modal{{ compet.id }}">More info</a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <!-- Modal competition -->
            <div class="modal fade pt-5" id="modal{{ compet.id }}" tabindex="-1" role="dialog"
                 aria-labelledby="exampleModalLabel" aria-hidden="true">
                <div class="modal-dialog " role="document">
                    <div class="modal-content">

                                <div class="modal-header">
                                    <div class="col-8">
                                        <h5 class="modal-title" id="exampleModalLabel">{{ compet.title }}</h5>
                                    </div>
                                    <div class="col-4   ">
                                        <div class="row pb-1">
                                            {% if compet.is_competition_opened %}
                                                <span class="badge badge-success"
                                                      style="background-color: #74DA47; border-color: #74DA47; color: #000">In progress</span>
                                            {% elif compet.is_inscription_opened %}
                                                <span class="badge badge-warning"
                                                      style="background-color: #dacb47; border-color: #dacb47; color: #000">Inscriptions</span>
                                            {% else %}
                                                <span class="badge badge-danger"
                                                      style="background-color: #EF3B3B; border-color: #EF3B3B; color: #000">Closed</span>
                                            {% endif %}
                                        </div>
                                        <div class="row">
                                            {% if compet.is_inscription_opened %}
                                                <span class="badge badge-success"
                                                      style="background-color: #74DA47; border-color: #74DA47; color: #000">Inscriptions opened</span>
                                            {% else %}
                                                <span class="badge badge-danger"
                                                      style="background-color: #EF3B3B; border-color: #EF3B3B; color: #000">Inscriptions closed</span>
                                            {% endif %}
                                        </div>
                                    </div>
                                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                        <span aria-hidden="true">&times;</span>
                                    </button>
                                </div>
                                <div class="modal-body">
                                    <div class="col-12">
                                        <div class="row">
                                            <h6><p class="font-weight-bold d-inline">Owner:</p> <a href="{% url "account:user_detail" compet.owner.pk %}">{{ compet.owner }}</a></h6>
                                        </div>
                                        <div class="row">
                                            <p class="font-weight-bold d-inline">Description: </p> <p class="d-inline"> {{ compet.description|slice:"0:240" }}...</p>
                                        </div>
                                        <br>
                                    </div>
                                    <div class="container row">
                                        <h6><p class="font-weight-bold d-inline">Date:</p> {{ compet.data_start_competition|date:"SHORT_DATE_FORMAT" }} -
                                            {{ compet.data_finish_competition|date:"SHORT_DATE_FORMAT" }}</h6>
                                    </div>
                                    <div class="container row">
                                        <h6><p class="font-weight-bold d-inline">Time:</p> {{ compet.data_start_competition|time }}
                                            - {{ compet.data_finish_competition|time }}</h6>
                                    </div>
                                </div>
                                <div class="modal-footer">
                                        <a href='{% url "competition:detail" compet.id %}' type="button"
                                                    class="btn btn-outline-primary ">Go to competition page</a>
                                        <div class="float-right">
                                        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                                        </div>
                                </div>
                            </div>
                </div>
            </div>
        {% endfor %}
    </div>
</div>

apps/league/templates/home/gen.html
{% load static %}
<div class="container-fluid text-center">
    <img class="center-fit" width="60%" src="{% static 'imgs/CodeleagueTransp.png' %}" alt="Architecture">
</div>
<div class="mw-100 text-center">
    <div class="btn-group btn-group-lg mw-100" role="group" aria-label="Basic example">
    <a class="btn  btn-outline-primary mw-100" href="{% url 'account:signup' %}">Sign Up</a>

    <a class="btn  btn-outline-secondary mw-100" href="{% url 'account:login' %}">Login</a>
    </div>
</div>