apps/account/urls.py
from django.urls import path, include
from django.contrib.auth.views import LoginView
from django.views.generic.base import TemplateView
from apps.account import forms, views

app_name = 'account'
urlpatterns = [
    path('login/', views.Login.as_view(), name='login'),
    path('signup/', views.SignUp.as_view(), name='signup'),
    path('', include('django.contrib.auth.urls')),
    path('u/<int:pk>/edit/', views.UpdateProfile.as_view(), name='edit'),
    path('u/<int:pk>/', views.UserDetail.as_view(), name='user_detail'),
    path('u/<int:pk>/participations/', views.UserParticipations.as_view(), name='participations'),
]

apps/category/urls.py
from django.urls import path
from apps.category import views
from apps.competition.apps import CompetitionConfig

app_name = 'category'
urlpatterns = [
    path('', views.ListCategories.as_view(), name='listofcategories'),
    path('search/', views.SearchCategories.as_view(), name="search"),
]

apps/competition/urls.py
from django.urls import path
from apps.competition import views
from apps.competition.apps import CompetitionConfig

app_name = 'competition'
urlpatterns = [
    path('', views.ListCompetition.as_view(), name='list'),
    path('create/', views.CreateCompetitionView.as_view(), name='createcompetition'),
    path('id/<int:pk>/', views.CompetitionDetail.as_view(), name='detail'),
    path('id/<int:pk>/edit/', views.CompetitionUpdate.as_view(), name='edit'),
    path('id/<int:pk>/delete/', views.CompetitionDelete.as_view(), name='delete'),
    path('id/<int:pk>/finish/', views.CompetitionFinish.as_view(), name='finish'),
    path('id/<int:pk>/create-team/', views.CreateTeam.as_view(), name='create-team'),
    path('id/<int:pk>/submit-answer/', views.PublishAnswerCompetition.as_view(), name='submit-answer'),
    path('id/<int:pk>/valorate-submitions/', views.RateAnswerCompetition.as_view(), name='valorate-submitions'),

    path('search/', views.SearchCompetitions.as_view(), name="search"),
]

apps/league/urls.py
from django.urls import path
from apps.league import views

app_name='league'
urlpatterns = [
    path('', views.Home.as_view(), name='home'),
    path('info/', views.Info.as_view(), name='info'),
]

codeleague/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic.base import TemplateView

urlpatterns = [
                  path('', include('apps.league.urls')),
                  path('admin/', admin.site.urls),
                  path('accounts/', include('apps.account.urls')),
                  path('competition/', include('apps.competition.urls')),
                  path('category/', include('apps.category.urls')),
              ] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no"/>

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
          integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous"/>

    <title>Codeleague | {% block title %}{% endblock %}</title>
</head>

<body>
<!-- Optional JavaScript -->
<!-- jQuery first, then Popper.js, then Bootstrap JS -->
{% include "header.html" %}
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
        integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
        crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
        integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1"
        crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
        integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM"
        crossorigin="anonymous"></script>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
<!-- Popper JS -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
    <div class="pt-1 px-5">
        <div class="px-4 py-5">
            {% block content %}
            {% endblock %}
        </div>
    </div>
</body>

</html>

templates/header.html
<header>
    <nav class="navbar fixed-top navbar-light justify-content-between navbar-expand-lg px-4" style="background-image: linear-gradient(15deg, #87e0e4 0%, #f0d660 100%);" role="navigation">
        <a class="navbar-brand pl-5" href="/">Codeleague</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav mr-auto">
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'league:info' %}">Info </a>
                    </li>
                    {% if user.is_authenticated %}
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Profile</a>
                            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                                <a class="dropdown-item" href="{% url 'account:user_detail' user.pk %}">View</a>
                                <a class="dropdown-item" href="{% url 'account:edit' user.pk %}">Edit</a>
                                <a class="dropdown-item" href="{% url 'account:participations' user.pk %}">Participations</a>
                            </div>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'competition:list' %}">Competitions</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'category:listofcategories' %}">Categories</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'competition:createcompetition' %}">Create competition</a>
                        </li>
                        <li class="nav-item px-3">
                            <a class="btn btn-outline-secondary" href="{% url 'account:logout' %}">Logout</a>
                        </li>
                    {% else %}
                        <li class="nav-item">
                            <a class="btn btn-outline-primary" href="{% url 'account:signup' %}">Sign Up</a>
                            <a class="btn btn-outline-secondary" href="{% url 'account:login' %}">Login</a>
                        </li>
                    {% endif %}
                </ul>

                <ul class="navbar-nav ml-auto px-5">
                    {% if user.is_authenticated %}
                        <form class="form-inline" action="{% url 'competition:search' %}" method="get">
                            <input name="q-comp" class="form-control mr-sm-2" type="search" placeholder="Search competitions" aria-label="Search">
                            <button class="btn btn-outline-secondary my-2 my-sm-0" type="submit">Search</button>
                        </form>
                    {% endif %}
                </ul>
        </div>
    </nav>

</header>