apps/account/urls.py
from django.urls import path, include
from django.contrib.auth.views import LoginView
from django.views.generic.base import TemplateView
from apps.account import forms, views

app_name = 'account'
urlpatterns = [
    path('login/', views.Login.as_view(), name='login'),
    path('signup/', views.SignUp.as_view(), name='signup'),
    path('', include('django.contrib.auth.urls')),
    path('u/<int:pk>/edit/', views.UpdateProfile.as_view(), name='edit'),
    path('u/<int:pk>/', views.UserDetail.as_view(), name='user_detail'),
    path('u/<int:pk>/participations/', views.UserParticipations.as_view(), name='participations'),
]

apps/league/urls.py
from django.urls import path
from apps.league import views

app_name='league'
urlpatterns = [
    path('', views.Home.as_view(), name='home'),
    path('info/', views.Info.as_view(), name='info'),
]

codeleague/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic.base import TemplateView

urlpatterns = [
                  path('', include('apps.league.urls')),
                  path('admin/', admin.site.urls),
                  path('accounts/', include('apps.account.urls')),
                  path('competition/', include('apps.competition.urls')),
                  path('category/', include('apps.category.urls')),
              ] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

apps/account/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser


# Create your models here.
class LeagueUser(AbstractUser):
    github_link = models.URLField(verbose_name='GitHub Link', max_length=75)

apps/account/forms.py
from django import forms
from django.contrib.auth import forms as auth_forms
from apps.league import models
from crispy_forms.helper import FormHelper

class AuthenticationForm(auth_forms.AuthenticationForm):
    username = forms.CharField(
        widget=forms.TextInput(
            attrs={
                'class': 'form-control',
                'placeholder': 'Type your username',
            }
        )
    )

    password = forms.CharField(
        widget=forms.PasswordInput(
            attrs={
                'class': 'form-control',
                'placeholder': 'Type your password'
            }
        )
    )

    # Defining custom error message for invalid login.
    error_messages = {
        'invalid_login': ("Invalid username and/or password."),
    }

    # Verify that the user is active before allowing login.
    def confirm_login_allowed(self, user):
        if not user.is_active:
            raise forms.ValidationError("This account is still inactive.", code='inactive', )

    def __init__(self, *args, **kwargs):
        super(AuthenticationForm, self).__init__(*args, **kwargs)
        self.helper = FormHelper(self)


class UserCreationForm(auth_forms.UserCreationForm):
    # A form for creating new users. It includes an additional field not used by default (email).
    class Meta:
        model = models.LeagueUser
        fields = ('username', 'email')

    def __init__(self, *args, **kwargs):
        super(UserCreationForm, self).__init__(*args, **kwargs)
        self.helper = FormHelper(self)


class UserChangeForm(auth_forms.UserChangeForm):
    # A form for updating new users.
    class Meta:
        model = models.LeagueUser
        fields = ('username',)

    def __init__(self, *args, **kwargs):
        super(UserChangeForm, self).__init__(*args, **kwargs)
        self.helper = FormHelper(self)

apps/account/views.py
from django.contrib.auth import get_user_model
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.contrib.auth.models import User
from django.contrib.auth.views import LoginView
from django.urls import reverse_lazy
from django.views import generic
from django import http
from django.views.generic import DetailView, UpdateView
from django.views.generic.edit import ModelFormMixin

from apps.account.forms import UserCreationForm, AuthenticationForm
from apps.account.models import LeagueUser
from apps.league.models import Team, Competition


class UpdateProfile(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    model = LeagueUser
    fields = ['username', 'github_link']
    template_name = 'update_profile.html'

    def get_context_data(self, **kwargs):
        context = {}
        return super().get_context_data(**context)

    def test_func(self):
        user = LeagueUser.objects.get(pk=self.kwargs['pk'])
        return user.pk == self.request.user.pk

    def get_success_url(self):
        return reverse_lazy('account:user_detail', kwargs={'pk': self.kwargs.get('pk')})


class SignUp(generic.CreateView):
    form_class = UserCreationForm
    success_url = reverse_lazy('account:login')
    template_name = 'sign_up.html'


# We are using reverse_lazy because for all generic class-based views the urls
# are not loaded when the file is imported, so we have to use the lazy form of
# reverse to load them later when they are available.

class UserDetail(LoginRequiredMixin, DetailView):
    template_name = "account.html"
    context_object_name = 'detailuser'
    model = LeagueUser

    def get_context_data(self, **kwargs):
        context = super(UserDetail, self).get_context_data(**kwargs)
        return context


class Login(LoginView):
    authentication_form = AuthenticationForm
    success_url = reverse_lazy('account:login')
    redirect_field_name = 'redirect_to'


class UserParticipations(LoginRequiredMixin, generic.TemplateView):
    template_name = "participations/participate.html"

    def get_context_data(self, **kwargs):
        context = super(UserParticipations, self).get_context_data(**kwargs)
        context['teams'] = Team.objects.filter(members=self.kwargs.get('pk'))
        context['competitions'] = []
        context['duser'] = LeagueUser.objects.get(pk=self.kwargs.get('pk'))
        for team in context['teams']:
            context['competitions'].append(Competition.objects.get(pk=team.competition.pk))
        context.update(kwargs)
        return context

apps/account/templates/account.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Your account{% endblock %}

{% block content %}
    <div class="container p-6">
        <div class="jumbotron p">
            {% if user.is_authenticated %}
                {% if user == detailuser %}
                    <a href="{% url 'account:edit' user.pk %}"
                       class="btn btn-outline-primary float-right">
                        <img width="20px"
                             src="{% static 'imgs/icons/edit.png' %}">Edit
                    </a>
                {% endif %}
                <h1>Hey, it's {{ detailuser.username }}</h1>
                <p>You can see your account details here</p>
                <div class="card">
                    <div class="card-body">

                        <p>Github Url: <a href="{{ detailuser.github_link }}" class="
                                          text-decoration-none">{{ detailuser.github_link }}</a></p>
                    </div>
                </div>
            {% else %}
                <p>You are not logged in. Log in to see your profile</p>
            {% endif %}
        </div>
    </div>
{% endblock %}

apps/account/templates/sign_up.html
{% extends 'base.html' %}
{% load crispy_forms_filters %}
{% block title %}Sign Up{% endblock %}

{% block content %}
    {% if user.is_authenticated %}
        <div class="alert alert-warning" role="alert">
            Hey, {{ user.username }}. You have already authenticated.
        </div>
    {% endif %}
    <div class="jumbotron">
        {% if user.is_authenticated %}

            <h1>What can you do now?</h1>
            <div class="row">
                <div class="col-12 col-md-4 py-2">
                    <div class="card">
                        <div class="card-body">
                            <h5 class="card-title">Compete!</h5>
                            <p class="card-text">Find a competition and enjoy programming! That's what you have
                                registered, didn't you?</p>
                            <a href="{% url 'league:home' %}" class="btn btn-primary float-right">Let's hack</a>
                        </div>
                    </div>
                </div>
                <div class="col-12 col-md-4 py-2">
                    <div class="card">
                        <div class="card-body">
                            <h5 class="card-title">Update your profile!</h5>
                            <p class="card-text">A cool profile means a cool hacker. Let's update your profile.</p>
                            <a href="{% url 'league:home' %}" class="btn btn-primary float-right">My profile</a>
                        </div>
                    </div>
                </div>
                <div class="col-12 col-md-4 py-2">
                    <div class="card">
                        <div class="card-body">
                            <h5 class="card-title">Create a competition!</h5>
                            <p class="card-text">If you find a competition that would be enjoyable? Create one!</p>
                            <a href="{% url 'competition:create-competition' %}" class="btn btn-primary float-right">Creator</a>
                        </div>
                    </div>
                </div>
            </div>
        {% else %}


            <div class="container">
                <div class="row d-flex justify-content-center">
                    <div class="col-10">
                        <h2>Sign up</h2>
                        <form method="post">
                            {% csrf_token %}
                            <!--
                                      csrf_token is a tag for security concerns, namely to prevent CSRF Attack.
                                      https://www.netsparker.com/blog/web-security/csrf-cross-site-request-forgery/
                                      -->
                            {{ form|crispy }}
                            <button class="btn btn-primary" value="login" type="submit">Login</button>
                        </form>

                    </div>
                </div>
            </div>

        {% endif %}
    </div>
{% endblock %}

apps/account/templates/update_profile.html
{% extends 'base.html' %}
{% load crispy_forms_filters %}

{% block title %}Editing Profile{% endblock %}
{% load crispy_forms_tags %}
{% block content %}
    <div class="jumbotron">
    <h1>Hi, {{ leagueuser.username }}</h1>
        <form method="post">{% csrf_token %}
            {{ form|crispy }}
            <input class="btn btn-success" type="submit" value="Update">
        </form>
    </div>
{% endblock %}