apps/account/urls.py
from django.urls import path, include
from django.contrib.auth.views import LoginView
from django.views.generic.base import TemplateView
from apps.account import forms, views

app_name = 'account'
urlpatterns = [
    path('login/', views.Login.as_view(), name='login'),
    path('signup/', views.SignUp.as_view(), name='signup'),
    path('', include('django.contrib.auth.urls')),
    path('u/<int:pk>/edit/', views.UpdateProfile.as_view(), name='edit'),
    path('u/<int:pk>/', views.UserDetail.as_view(), name='user_detail'),
    path('u/<int:pk>/participations/', views.UserParticipations.as_view(), name='participations'),
]

apps/competition/urls.py
from django.urls import path
from apps.competition import views
from apps.competition.apps import CompetitionConfig

app_name = 'competition'
urlpatterns = [
    path('', views.ListCompetition.as_view(), name='list'),
    path('create/', views.CreateCompetitionView.as_view(), name='createcompetition'),
    path('id/<int:pk>/', views.CompetitionDetail.as_view(), name='detail'),
    path('id/<int:pk>/edit/', views.CompetitionUpdate.as_view(), name='edit'),
    path('id/<int:pk>/delete/', views.CompetitionDelete.as_view(), name='delete'),
    path('id/<int:pk>/finish/', views.CompetitionFinish.as_view(), name='finish'),
    path('id/<int:pk>/create-team/', views.CreateTeam.as_view(), name='create-team'),
    path('id/<int:pk>/submit-answer/', views.PublishAnswerCompetition.as_view(), name='submit-answer'),
    path('id/<int:pk>/valorate-submitions/', views.RateAnswerCompetition.as_view(), name='valorate-submitions'),

    path('search/', views.SearchCompetitions.as_view(), name="search"),
]

codeleague/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic.base import TemplateView

urlpatterns = [
                  path('', include('apps.league.urls')),
                  path('admin/', admin.site.urls),
                  path('accounts/', include('apps.account.urls')),
                  path('competition/', include('apps.competition.urls')),
                  path('category/', include('apps.category.urls')),
              ] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

apps/competition/forms.py
from django.contrib.auth import get_user_model
from django.forms import SplitDateTimeWidget
from django.contrib.admin import widgets
from apps.league.models import Competition, Team, Submit
from django import forms
from django.forms.utils import to_current_timezone


class CompetitionCreationForm(forms.ModelForm):
    files = forms.FileField(widget=forms.ClearableFileInput(attrs={'multiple': True}), required=False)
    data_start_inscription = forms.SplitDateTimeField()
    data_finish_inscription = forms.SplitDateTimeField()
    data_start_competition = forms.SplitDateTimeField()
    data_finish_competition = forms.SplitDateTimeField()

    class Meta:
        model = Competition
        fields = '__all__'
        exclude = ['categories', 'owner', 'files']
        widgets = {
            'data_start_inscription': forms.SplitDateTimeWidget(),
            'data_finish_inscription': forms.SplitDateTimeWidget(),
            'data_start_competition': forms.SplitDateTimeWidget(),
            'data_finish_competition': forms.SplitDateTimeWidget(),
        }


class TeamCreationForm(forms.ModelForm):
    class Meta:
        model = Team
        fields = ['name']


class TeamJoinForm(forms.ModelForm):
    action = forms.CharField(max_length=30, required=False)

    class Meta:
        model = Team
        fields = []


class DownloadFile(forms.ModelForm):
    action = forms.CharField(max_length=30, required=False)

    class Meta:
        model = Competition
        fields = []


class TeamLeaveForm(forms.ModelForm):
    class Meta:
        model = Team
        fields = []


class PublishAnswerForm(forms.ModelForm):
    files = forms.FileField(widget=forms.ClearableFileInput(attrs={'multiple': True}), required=False)

    class Meta:
        model = Submit
        fields = '__all__'
        exclude = ['files', 'team_id']

apps/competition/views.py
from django import http
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.urls import reverse_lazy
from django.views.generic.edit import UpdateView
from django.views import generic
from django.shortcuts import render
from apps.competition.forms import CompetitionCreationForm, TeamCreationForm, TeamJoinForm, TeamLeaveForm, \
    PublishAnswerForm
from apps.league.models import Team, Competition, Category, Files, Ranking

import os, boto3, datetime,random

s3 = boto3.resource('s3', aws_access_key_id=str(os.getenv('AWS_KEY')),
                    aws_secret_access_key=str(os.getenv('AWS_SECRET')))
s3_client = boto3.client('s3', aws_access_key_id=str(os.getenv('AWS_KEY')),
                         aws_secret_access_key=str(os.getenv('AWS_SECRET')))


class ListCompetition(LoginRequiredMixin, generic.ListView):
    model = Competition
    template_name = 'competition/list.html'
    context_object_name = 'competitions'
    login_url = reverse_lazy('account:login')

    def get_queryset(self, *args, **kwargs):
        return self.model.objects.all().order_by('-data_finish_competition')


class CreateCompetitionView(LoginRequiredMixin, generic.CreateView):
    login_url = reverse_lazy('account:login')
    form_class = CompetitionCreationForm
    model = Competition
    template_name = 'competition/create.html'

    def get_success_url(self, **kwargs):
        return reverse_lazy('competition:detail', kwargs={'pk': kwargs.get('pk')})
        # return reverse_lazy('competition:detail', kwargs={'pk': self.request.user.pk})

    def form_valid(self, form):
        competition = form.save(commit=False)
        competition.owner = self.request.user
        files = self.request.FILES.getlist('files')
        competition.save()
        for file_name in files:
            datecreated = datetime.datetime.now()
            s3.Bucket(os.getenv('AWS_BUCKET')).put_object(
                Key="competition/" + str(competition.id) + "_" + str(datecreated) + "_" + str(file_name),
                Body=file_name)
            file_data = Files.create(str(file_name),
                                     "competition/" + str(competition.id) + "_" + str(datecreated) + "_" + str(
                                         file_name))
            file_data.save()
            competition.files.add(file_data)
        competition.save()
        return http.HttpResponseRedirect(self.get_success_url(pk=competition.id))


class CompetitionUpdate(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    model = Competition
    fields = ['title', 'description']
    template_name = 'competition/competition_update_form.html'
    context_object_name = 'competition'

    def get_context_data(self, **kwargs):
        context = {}
        return super().get_context_data(**context)

    def test_func(self):
        competition = Competition.objects.get(pk=self.kwargs['pk'])
        return competition.owner.pk == self.request.user.pk

    def form_valid(self, form):
        competition = form.save()
        delete = False
        res = []
        for update_file in competition.files.all():
            if (self.request.POST.get('delete' + str(update_file.id))):
                res.append({'Key': update_file.file_bucket})
                competition.files.remove(update_file)
                update_file.delete()
                delete = True
            else:
                update_file.title = self.request.POST.get('title' + str(update_file.id))
                update_file.save()
        if delete: s3.Bucket(os.getenv('AWS_BUCKET')).delete_objects(Delete={'Objects': res})
        competition.save()
        files = self.request.FILES.getlist('files')
        for file_name in files:
            datecreated = datetime.datetime.now()
            s3.Bucket(os.getenv('AWS_BUCKET')).put_object(
                Key="competition/" + str(competition.id) + "_" + str(datecreated) + "_" + str(file_name),
                Body=file_name)
            file_data = Files.create(str(file_name),
                                     "competition/" + str(competition.id) + "_" + str(datecreated) + "_" + str(
                                         file_name))
            file_data.save()
            competition.files.add(file_data)
        competition.save()
        return http.HttpResponseRedirect(self.get_success_url(pk=competition.id))

    def get_success_url(self, **kwargs):
        return reverse_lazy('competition:detail', kwargs={'pk': kwargs.get('pk')})


class CompetitionDelete(LoginRequiredMixin, UserPassesTestMixin, generic.DeleteView):
    model = Competition
    template_name = 'competition/delete.html'
    success_url = reverse_lazy('competition:list')

    def get_context_data(self, **kwargs):
        context = {}
        return super().get_context_data(**context)

    def get_success_url(self):
        return reverse_lazy('competition:list')

    def test_func(self):
        competition = Competition.objects.filter(id=self.kwargs.get(self.pk_url_kwarg))[0]
        if competition.owner != self.request.user or competition.is_competition_opened():
            return False
        return True

    def form_valid(self, form):
        if self.request.method == 'POST':
            competition = Competition.objects.filter(id=self.kwargs['pk'])[0]
            if competition.is_competition_opened() is False and competition.owner == self.request.user:
                action = self.request.POST.get('action')
                if action == 'delete':
                    competition.delete(self.request.user.pk)

                return http.HttpResponseRedirect(self.get_success_url())


class CompetitionDetail(LoginRequiredMixin, generic.DetailView, generic.CreateView):
    login_url = reverse_lazy('account:login')
    redirect_field_name = 'redirect_to'
    context_object_name = 'competition'
    template_name = 'competition/detail.html'
    success_url = reverse_lazy('competition:join-team')
    form_class = TeamJoinForm

    queryset = Competition.objects.all()

    def get_context_data(self, **kwargs):
        context = {}
        r = lambda: random.randint(0,255)
        context['data'] = [["puntuation", "table", { 'role': 'style' }]]

        context['user'] = self.request.user
        competition = Competition.objects.get(pk=self.kwargs.get('pk'))
        teams_of_competition = Team.objects.filter(competition=competition)
        context['groups'] = teams_of_competition.order_by('-ranking__score')
        context['haveTeam'] = False
        for group in context['groups']:
            print(group)
            if group.submition and len(context['data']) < 10:
                if group.ranking:
                    context['data'].append(
                        [group.name, int(group.ranking.score), 'color: #%02X%02X%02X' % (r(), r(), r())])
                else:
                    context['data'].append(
                        [group.name, 0, 'color: #%02X%02X%02X' % (r(), r(), r())])
            if context['user'] in group.members.all():
                context['haveTeam'] = True
                break
        context.update(kwargs)
        competition = Competition.objects.filter(id=self.kwargs.get(self.pk_url_kwarg))[0]
        files = competition.files.all()
        context['files'] = []
        for competition_file in files:

            context['files'].append((competition_file.title, s3_client.generate_presigned_url('get_object', Params={
                'Bucket': os.getenv('AWS_BUCKET'), 'Key': competition_file.file_bucket}, ExpiresIn=100)))
        return super().get_context_data(**context)

    def form_valid(self, form):
        competition = Competition.objects.filter(id=self.kwargs['pk'])[0]
        action = self.request.POST.get('action')
        if competition.is_inscription_opened():
            team = Team.objects.filter(id=self.request.POST.get('teamId'))[0]
            if action == 'join':
                team.members.add(self.request.user.pk)
                team.save()
            elif action == 'leave':
                team.members.remove(self.request.user.pk)
                team.save()
                if len(team.members.all()) == 0:
                    team.delete()
            return http.HttpResponseRedirect(self.get_success_url())
        return http.HttpResponseForbidden()

    def get_success_url(self):
        return reverse_lazy('competition:detail', kwargs={'pk': self.kwargs['pk']})


class CreateTeam(LoginRequiredMixin, UserPassesTestMixin, generic.CreateView):
    login_url = reverse_lazy('account:login')
    template_name = 'team/create.html'
    success_url = reverse_lazy('competition:create-team')
    queryset = Competition.objects.all()
    form_class = TeamCreationForm

    def get_context_data(self, **kwargs):
        context = {}

        return super().get_context_data(**context)

    def get_success_url(self):
        return reverse_lazy('competition:detail', kwargs={'pk': self.kwargs['pk']})

    def test_func(self):
        competition = Competition.objects.filter(id=self.kwargs.get(self.pk_url_kwarg))[0]
        if competition.owner == self.request.user:
            return False
        teams = Team.objects.filter(competition=self.kwargs.get(self.pk_url_kwarg))
        for team in teams:
            if self.request.user in team.members.all():
                return False
        return True

    def form_valid(self, form):
        team = form.save(commit=False)
        team.competition = Competition.objects.get(pk=self.kwargs['pk'])
        team.save()
        team.members.add(self.request.user.pk)
        team.save()
        return http.HttpResponseRedirect(self.get_success_url())


class SearchCompetitions(LoginRequiredMixin, generic.TemplateView):
    context_object_name = 'context'
    template_name = 'search/list.html'

    def get_context_data(self, **kwargs):
        query = self.request.GET.get('q-comp')
        competitions = Competition.objects.filter(title__contains=query).union(

apps/competition/templates/competition/competition_update_form.html
{% extends 'base.html' %}
{% load crispy_forms_filters %}

{% block title %}Sign Up{% endblock %}
{% load crispy_forms_tags %}
{% block content %}
    <div class="jumbotron">
        <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
            {{ form|crispy }}
            {% if competition.files.all|length > 0%}
                <div class="row">
                    <div class="col-2"><h5>File</h5></div>
                    <div class="col-4"><h5>Custom file name</h5></div>
                </div>  
                {% for file in competition.files.all %}
                    <div type="row justify-content-md-center">
                        <div class="row">
                            <div class="col-2">{{file.title}}</div>
                            <div class="col-4"><input type="text" class="form-control" name="title{{file.id}}" id="title{{file.id}}" value="{{file.title}}"></div>
                            <div class="form-group form-check">
                                <input type="checkbox" class="form-check-input" id="delete{{file.id}}" name="delete{{file.id}}">
                                <label class="form-check-label"  for="exampleCheck1">Delete</label>
                            </div>  
                        </div>    
                    </div>
                {% endfor %}
            {% endif %}
            <div class="form-group">
                <label for="exampleFormControlFile1">Add new files</label>
                <input type="file" class="form-control-file" id="exampleFormControlFile1" name="files" multiple>
            </div>

            <input type="submit" name="update" value="update">
        </form>
    </div>
{% endblock %}

apps/competition/templates/competition/create.html
{% extends 'base.html' %}
{% load crispy_forms_filters %}

{% block title %}Sign Up{% endblock %}
{% load crispy_forms_tags %}
{% block content %}
    <div class="jumbotron">

        <div class="container">
            <div class="container col-10">
                <h1 >Creating your competition...</h1>
            </div>
            <div class="row d-flex justify-content-center">
                <div class="container col-10">
                    <form method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        {{ form|crispy }}
                        <button class="btn btn-warning" id="create" name="create" value="create" type="submit">Sign Up</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

apps/competition/templates/competition/detail.html
{% extends 'base.html' %}




{% load static %}
{% block title %}{{competition.title}}{% endblock %}
{% block content %}
<script type="text/javascript" src="https://www.google.com/jsapi"></script>
<script type="text/javascript">
    var a = {{ data|safe }};

    google.load('visualization', '1.0', {'packages':['corechart']});
    google.setOnLoadCallback(drawChart);
    function drawChart() {
        var data = new google.visualization.arrayToDataTable(a);
        var view = new google.visualization.DataView(data);

        view.setColumns([0, 1,
                    { calc: "stringify",
                        sourceColumn: 1,
                        type: "string",
                        role: "annotation" },
                    2]);
        var options = {
            title: "Puntuation statistics",
            width: 380,
            height: 400,
            bar: {groupWidth: "95%"},
            legend: { position: "none" },
        };
        var chart = new google.visualization.ColumnChart(document.getElementById("columnchart_values"));
        chart.draw(view, options);
    }
</script>
    <div class="jumbotron">
        <div class="container ">
            {% if competition.owner != user and competition.is_inscription_opened and haveTeam == False%}
            <a name="create_team" href='{% url 'competition:create-team' competition.id %}' class="btn btn-primary float-right btn-lg">Create a Group!
            </a>
            {% elif competition.owner == user%}
                <div class="float-right pr-3">
                <a href="{% url 'competition:edit' competition.pk %}"
                   class="btn btn-outline-primary float-right btn-lg">
                    <img width="20px"
                         src="{% static 'imgs/icons/edit.png' %}">Edit
                </a>
                </div>
                {% if competition.is_competition_ended and competition.finalized == False %}
                    <div class="float-right pr-3">
                    <a href="{% url 'competition:valorate-submitions' competition.pk %}"
                    class="btn btn-outline-primary float-right btn-lg">
                        <img width="20px"
                            src="{% static 'imgs/icons/edit.png' %}">Valorate
                    </a>
                    </div>                
                {% endif %}
                {% if not competition.is_competition_open %}
                <div class="float-right pr-3">
                <a name="delete_competition" href="{% url 'competition:delete' competition.pk %}" class="btn btn-danger float-right">Delete Competition</a>
                </div>
                {% endif %}
            {% endif %}

            <div class="row">
                <div class="col-10">
                    <h1>{{ competition.title }}</h1>
                    <p>{{ competition.description }}</p>
                </div>
                <div class="col-2">
                    {% if haveTeam and competition.is_competition_opened %}
                    <div class="float-left container">
                    <a href='{% url "competition:submit-answer" competition.id %}' name="submit_resolution" type="button"
                                       class="btn btn-primary">Publish solution</a>
                        </div>
                    {% endif %}
                </div>

            </div>

            <div class="row">
                <div class="col-4">
                    <ul class="list-unstyled">
                        {% if competition.finalized %}
                        <div class="card ">
                            <div class="" id="columnchart_values"></div>
                        </div>
                        {% endif %}
                    {% if  competition.files.all|length > 0 %}
                        <h3 class="mt-0 mb-1">Files</h3>
                        {% for file in files %}
                            <li class="media">
                            <div style="margin:5px" class="container">
                                <div class="media-body">
                                <a href="{{file.1}}" download="{{file.0}}" class="btn btn-primary btn-sm">
                                    <img width="20px" src="{% static 'imgs/icons/document.svg' %}" class="mr-3">{{file.0}}
                                </a>
                                </div>
                            </div>
                            </li>
                        {% endfor %}
                    {% endif %}
                    </ul>
                </div>
                <div class="col-8">{% include "team/join.html" %}</div>
            </div>

        </div>
    </div>
{% endblock %}

apps/competition/templates/competition/list.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Home{% endblock %}

{% block content %}
    <div class="jumbotron">
        {% load static %}
        <div class="container" xmlns:competition="http://www.w3.org/1999/xhtml">
            <h1>List of Competitions</h1>
            <br>
            <div class="row pb-3">
                {% for compet in competitions %}
                    <div class="col-6 pb-3 d-flex align-items-stretch">
                        <div class="card"  style="width: 36rem;">
                            <div class="card-body">
                                {% if compet.owner == user %}
                                    <a href="{% url 'competition:edit' compet.pk %}"
                                       class="btn btn-outline-primary float-right">
                                        <img width="20px"
                                             src="{% static 'imgs/icons/edit.png' %}">Edit
                                    </a>
                                {% endif %}
                                <div class="row">
                                    <div class="col-12">
                                        <h4 class="card-title">{{ compet.title }}{% if compet.is_competition_opened %}
                                            <span class="badge badge-success"
                                                  style="background-color: #74DA47; border-color: #74DA47; color: #000">In progress</span>
                                        {% elif compet.is_inscription_opened %}
                                            <span class="badge badge-warning"
                                                  style="background-color: #dacb47; border-color: #dacb47; color: #000">Inscriptions</span>
                                        {% else %}
                                            <span class="badge badge-warning"
                                                  style="background-color: #EF3B3B; border-color: #EF3B3B; color: #000">Closed</span>

                                        {% endif %}</h4>
                                    </div>

                                </div>
                                {% if compet.is_inscription_opened %}
                                    <span class="badge badge-success"
                                          style="background-color: #74DA47; border-color: #74DA47; color: #000">Inscriptions opened</span>
                                {% else %}
                                    <span class="badge badge-danger"
                                          style="background-color: #EF3B3B; border-color: #EF3B3B; color: #000">Inscriptions closed</span>
                                {% endif %}

                                <p class="card-text pt-3">
                                    {{ compet.description|slice:"0:200" }}...


                                </p><br>
                                <div class="row">
                                    <div class="col-9">
                                        <div class="container row">
                                            <h6>Date: {{ compet.data_start_competition|date:"SHORT_DATE_FORMAT" }} -
                                                {{ compet.data_finish_competition|date:"SHORT_DATE_FORMAT" }}</h6>
                                        </div>
                                        <div class="container row">
                                            <h6>Time: {{ compet.data_start_competition|time }}
                                                - {{ compet.data_finish_competition|time }}</h6>
                                        </div>
                                    </div>

                                    <div class="col-3">
                                        <a href="#" class="btn badge-pill btn-primary float-right" data-toggle="modal"
                                           data-target="#modal{{ compet.id }}">More info</a>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <!-- Modal competition -->
            <div class="modal fade pt-5" id="modal{{ compet.id }}" tabindex="-1" role="dialog"
                 aria-labelledby="exampleModalLabel" aria-hidden="true">
                <div class="modal-dialog " role="document">
                    <div class="modal-content">

                                <div class="modal-header">
                                    <div class="col-8">
                                        <h5 class="modal-title" id="exampleModalLabel">{{ compet.title }}</h5>
                                    </div>
                                    <div class="col-4   ">
                                        <div class="row pb-1">
                                            {% if compet.is_competition_opened %}
                                                <span class="badge badge-success"
                                                      style="background-color: #74DA47; border-color: #74DA47; color: #000">In progress</span>
                                            {% elif compet.is_inscription_opened %}
                                                <span class="badge badge-warning"
                                                      style="background-color: #dacb47; border-color: #dacb47; color: #000">Inscriptions</span>
                                            {% else %}
                                                <span class="badge badge-danger"
                                                      style="background-color: #EF3B3B; border-color: #EF3B3B; color: #000">Closed</span>
                                            {% endif %}
                                        </div>
                                        <div class="row">
                                            {% if compet.is_inscription_opened %}
                                                <span class="badge badge-success"
                                                      style="background-color: #74DA47; border-color: #74DA47; color: #000">Inscriptions opened</span>
                                            {% else %}
                                                <span class="badge badge-danger"
                                                      style="background-color: #EF3B3B; border-color: #EF3B3B; color: #000">Inscriptions closed</span>
                                            {% endif %}
                                        </div>
                                    </div>
                                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                        <span aria-hidden="true">&times;</span>
                                    </button>
                                </div>
                                <div class="modal-body">
                                    <div class="col-12">
                                        <div class="row">
                                            <h6><p class="font-weight-bold d-inline">Owner:</p> <a href="{% url "account:user_detail" compet.owner.pk %}">{{ compet.owner }}</a></h6>
                                        </div>
                                        <div class="row">
                                            <p class="font-weight-bold d-inline">Description: </p> <p class="d-inline"> {{ compet.description|slice:"0:240" }}...</p>
                                        </div>
                                        <br>
                                    </div>
                                    <div class="container row">
                                        <h6><p class="font-weight-bold d-inline">Date:</p> {{ compet.data_start_competition|date:"SHORT_DATE_FORMAT" }} -
                                            {{ compet.data_finish_competition|date:"SHORT_DATE_FORMAT" }}</h6>
                                    </div>
                                    <div class="container row">
                                        <h6><p class="font-weight-bold d-inline">Time:</p> {{ compet.data_start_competition|time }}
                                            - {{ compet.data_finish_competition|time }}</h6>
                                    </div>
                                </div>
                                <div class="modal-footer">
                                        <a href='{% url "competition:detail" compet.id %}' type="button"
                                                    class="btn btn-outline-primary ">Go to competition page</a>
                                        <div class="float-right">
                                        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                                        </div>
                                </div>
                            </div>
                </div>
            </div>
                {% endfor %}
            </div>
        </div>


    </div>
{% endblock %}